export const MAX_BROWSER_CONTEXTS = 8;
export const MAX_BROWSER_PAGES_PER_SESSION = 8;
export const MAX_BROWSER_PENDING_OPERATIONS = 32;

export const MAX_BROWSER_DIAGNOSTIC_ENTRIES = 256;
export const DEFAULT_BROWSER_DIAGNOSTIC_RESULT_ENTRIES = 50;
export const MAX_BROWSER_DIAGNOSTIC_RESULT_ENTRIES = 100;
export const MAX_BROWSER_DIAGNOSTIC_TEXT_BYTES = 4 * 1024;

export const MAX_BROWSER_SNAPSHOT_BYTES = 48 * 1024;
export const DEFAULT_BROWSER_SNAPSHOT_DEPTH = 12;
export const MAX_BROWSER_SNAPSHOT_DEPTH = 20;
export const MAX_BROWSER_RESULT_BYTES = 64 * 1024;

export const MAX_BROWSER_URL_BYTES = 8 * 1024;
export const MAX_BROWSER_PROJECTED_URL_BYTES = 2 * 1024;
export const MAX_BROWSER_ORIGIN_BYTES = 2 * 1024;
export const MAX_BROWSER_TITLE_BYTES = 512;
export const MAX_BROWSER_ID_BYTES = 128;
export const MAX_BROWSER_REF_BYTES = 64;
export const MAX_BROWSER_FINGERPRINT_BYTES = 1024;
export const MAX_BROWSER_INPUT_BYTES = 16 * 1024;
export const MAX_BROWSER_SCROLL_AMOUNT = 10_000;
export const MAX_BROWSER_WAIT_TEXT_BYTES = 4 * 1024;
export const MAX_BROWSER_SELECT_VALUES = 16;
export const MAX_BROWSER_SELECT_VALUE_BYTES = 4 * 1024;

export const DEFAULT_BROWSER_ACTION_TIMEOUT_MS = 10_000;
export const MAX_BROWSER_ACTION_TIMEOUT_MS = 30_000;
export const BROWSER_CLICK_SETTLE_TIMEOUT_MS = 500;
export const DEFAULT_BROWSER_NAVIGATION_TIMEOUT_MS = 30_000;
export const MAX_BROWSER_NAVIGATION_TIMEOUT_MS = 60_000;
export const DEFAULT_BROWSER_WAIT_TIMEOUT_MS = 10_000;
export const MAX_BROWSER_WAIT_TIMEOUT_MS = 30_000;
export const MAX_BROWSER_EXPLICIT_WAIT_MS = 5_000;

export const MAX_BROWSER_SCREENSHOT_BYTES = 8 * 1024 * 1024;
export const MAX_BROWSER_SCREENSHOTS_PER_SESSION = 32;
export const MAX_BROWSER_SCREENSHOT_SESSION_BYTES = 64 * 1024 * 1024;
